version: "3.1"

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webhook
    restart: always
    healthcheck:
      test: "curl -sS --fail 127.0.0.1:9000 || exit 1"
      interval: 120s
      timeout: 5s
      retries: 5
    volumes:
      - ./hooks/:/etc/webhook
      - ./scripts/:/scripts/
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.services.webhook.loadbalancer.server.port=9000
      - traefik.http.routers.webhook.rule=PathPrefix(`/webhook`)
      - traefik.http.routers.webhook.middlewares=webhook-stripprefix
      - traefik.http.middlewares.webhook-stripprefix.stripprefix.prefixes=/webhook

networks:
  traefik:
    external: true
